#!/usr/bin/env python
"""
The Open Device Daemon - Python Implementation

(C) 2008 Michael 'Mickey' Lauer <mlauer@vanille-media.de>
(C) 2008 Openmoko, Inc.

GPLv2 or later
"""

__version__ = "1.0.0"

import sys, os

try:
    from framework import controller
except ImportError:
    sys.path.append( os.path.dirname( os.path.abspath( os.path.curdir ) ) )
    from framework import controller

if __name__ == "__main__":
    c = controller.Controller( "%s/subsystems" % os.path.dirname( controller.__file__ ) )

    try:
        c.launch()
    except KeyboardInterrupt:
        print >>sys.stderr, "ctrl-c: exiting."
        c.shutdown()
        del c
