#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""
Interactive console for the freesmartphone.org framework

(C) 2008 Michael 'Mickey' Lauer <mlauer@vanille-media.de>
(C) 2008 Jan 'Shoragan' Lübbe <jluebbe@lasnet.de>
(C) 2008 Openmoko, Inc.

GPLv2 or later
"""

import os, sys, code
import dbus.service
import dbus.mainloop.glib
import dbus
from syslog import syslog, LOG_ERR, LOG_WARNING, LOG_INFO, LOG_DEBUG
import dbus, sys, atexit
from gobject import MainLoop

def handler( *args, **kwargs ):
    if kwargs["path"].startswith( "/org/freesmartphone" ):
        print "[SIGNAL]   %s.%s    from " % ( kwargs["interface"], kwargs["member"] ),
        print "%s via %s" % ( kwargs["path"], kwargs["sender"] )
        for arg in args[:-1]:
            print "%s, " % arg,
        print "%s" % args[-1]
        print ">>> ",
        sys.stdout.flush()

def getObject( bus, busname, objectpath ):
    return bus.get_object( busname, objectpath, follow_name_owner_changes=True )

def getInterface( bus, busname, objectpath, interface ):
    proxy = getObject( bus, busname, objectpath )
    return dbus.Interface( proxy, interface)

dbus.mainloop.glib.DBusGMainLoop( set_as_default=True )
mainloop = MainLoop()
bus = dbus.SystemBus()

# FIXME use introspection

# ogsmd device object
gsm = getObject( bus, "org.freesmartphone.ogsmd", "/org/freesmartphone/GSM/Device" )

# ogsmd server
hz = getInterface( bus,
    "org.freesmartphone.ogsmd",
    "/org/freesmartphone/GSM/Server",
    "org.freesmartphone.GSM.HZ" )

# odeviced objects
audio = getInterface( \
    bus,
    "org.freesmartphone.odeviced",
    "/org/freesmartphone/Device/Audio",
    "org.freesmartphone.Device.Audio" \
    )

# device
gsmdevice = getInterface( bus,
    "org.freesmartphone.ogsmd",
    "/org/freesmartphone/GSM/Device",
    "org.freesmartphone.GSM.Device" )
gsmsim = getInterface( bus,
    "org.freesmartphone.ogsmd",
    "/org/freesmartphone/GSM/Device",
    "org.freesmartphone.GSM.SIM" )
gsmnetwork = getInterface( bus,
    "org.freesmartphone.ogsmd",
    "/org/freesmartphone/GSM/Device",
    "org.freesmartphone.GSM.Network" )
gsmcall = getInterface( bus,
    "org.freesmartphone.ogsmd",
    "/org/freesmartphone/GSM/Device",
    "org.freesmartphone.GSM.Call" )
gsmpdp = getInterface( bus,
    "org.freesmartphone.ogsmd",
    "/org/freesmartphone/GSM/Device",
    "org.freesmartphone.GSM.PDP" )
gsmtest = getInterface( bus,
    "org.freesmartphone.ogsmd",
    "/org/freesmartphone/GSM/Device",
    "org.freesmartphone.GSM.Test" )

bus.add_signal_receiver( handler, None, None, None, None,
    sender_keyword = "sender",
    destination_keyword = "destination",
    interface_keyword = "interface",
    member_keyword = "member",
    path_keyword = "path" )

import rlcompleter, readline, atexit
readline.parse_and_bind( "tab: complete" )
try:
    readline.read_history_file( os.path.expanduser( "~/.framework-history" ) )
except IOError:
    pass
atexit.register( readline.write_history_file, os.path.expanduser( "~/.framework-history" ) )

def runmainloop():
    try:
        mainloop.run()
    except KeyboardInterrupt:
        mainloop.quit()
        sys.exit( 0 )

console = code.InteractiveConsole( locals() )
try:
    console.interact( "freesmartphone.org interactive command line" )
except KeyboardInterrupt:
    sys.exit( 0 )
