#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""
Minimal Netlink Message Dumper
(C) 2008 Michael 'Mickey' Lauer <mlauer@vanille-media.de>
GPLv2 or later
"""
import pprint
pp = pprint.PrettyPrinter( indent=4 )

from framework.cxnet.netlink.rtnl import *
p = rtnl_msg_parser()
s = rtnl_socket( groups=0xff )

while True:
    len, msg = s.recv()
    pp.pprint( p.parse( msg ) )
        
        
